export const SCORING_SCOPE = "SCORING_ENGINE";

export const SCORING_REJECTION_REASONS = {
  MISSING_TRADES: "MISSING_TRADES",
  MISSING_METRICS: "MISSING_METRICS",
  MIN_TRADING_DAYS: "MIN_TRADING_DAYS",
  MIN_TOTAL_TRADES: "MIN_TOTAL_TRADES",
  MIN_PROFIT_FACTOR: "MIN_PROFIT_FACTOR",
  MAX_DRAWDOWN: "MAX_DRAWDOWN",
  MIN_WIN_RATE: "MIN_WIN_RATE",
} as const;
